baseurl = "http://sw-saturn.github.io/blog"
title = "お気持ち表明"
author = "Kanta Demizu"
languageCode = "en-us"
theme = "tale"
canonifyurls = false
googleAnalytics = "UA-132342615-1"

[Author]
    name = "Kanta Demizu"