baseurl = "https://blog.sw-saturn.dev/"
title = "お気持ち表明"
author = "でみ"
languageCode = "en-us"
hasCJKLanguage = true
canonifyurls = false
theme = "robust"
enableEmoji = true
copyright = "&copy; 2021 でみ"

[Author]
    name = "でみ"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    # Fonts settings.
    googlefonts = "https://fonts.googleapis.com/css?family=Lato|Noto+Sans+JP&display=swap" # Optional, Include google fonts.
    fontfamily = "Lato, 'Noto Sans JP', 'Hiragino Kaku Gothic Pro', Meiryo, sans-serif" # Optional, Override body font family.
    logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[taxonomies]
    tag = "tags"

[params.author]
  thumbnail = "https://avatars.githubusercontent.com/Sw-Saturn"
  name = "でみ"
  description = "<center>プロフィールは<a href='https://sw-saturn.dev'>こちら</a>。</center>"

[outputs]
  page = [ "HTML", "AMP" ]
